### ISSUE TITLE
Serverside Rendering

### ISSUE THREAD

**Issue by ElectronicsArchiver** [nptnk/nptnk.github.io#5]
I was thinking of implementing sever-side rendering via Deno.

( Without Framework )

### Concept

```
Mods.yaml        -> | Deno -> | index.html
Recommended.yaml    |         | Style.css
Styles/Font.css     |         | Mods.json
Styles/Theme.css    |
Styles/Base.css     |
Styles/Animate.css  |
Template.html       |
```

<br>

The building process would be run locally with

```sh
deno task build
```

<br>

- This would allow to split up the CSS / JS into structured files instead of big blobs
- With the current feature set, reduce shipped JS to Zero
- Remove the need for shipping thumbnail information ( known what link it uses )
- Be more responsive / faster ( HTML > CSS > JS in terms of speed )

<br>

### Dependencies

This would only introduce Deno as a dependency, which is
avaiable on all platforms in a multitude of ways, provides
security restrictions and can be integrated into workflows.

<br>

**Comment by ElectronicsArchiver** [comment]
@nptnk Btw, either way, you have to switch to `GitHub Actions` in the `GitHub Pages` settings section of your repository, currently it still uses classic jerkyl rendering and displays the README instead of using the workflow!

**Comment by ElectronicsArchiver** [comment]
Welp, already finished implementing it #6

**Comment by ElectronicsArchiver** [comment]
@nptnk My second comment about GitHub actions is rather important, regarding what you see / don't see at https://nptnk.github.io/

**Comment by nptnk** [comment]
im really bad at using github so im just gonna make you a collaborator

**Comment by ElectronicsArchiver** [comment]
@nptnk Cool, sure let me set it up, if you want to
know more about how to use GitHub, just let me know~

**Comment by ElectronicsArchiver** [comment]
Actually, just being a collaborator doesn't
allow me to adjust GitHub Pages settings
not repository information ..

**Comment by ElectronicsArchiver** [comment]
Just so you know, the GitHub Pages source can be changed with:

**`Settings` Tab**  >  **Sidebar**  >  **`Pages`**  >  `Source` **Dropdown**  >  Select **`GitHub Actions`**

**Comment by nptnk** [comment]
i have got Github Actions selected do i need to do anything else?

**Comment by ElectronicsArchiver** [comment]
@nptnk Yes and no, while you activted actions, it seems you
also clicked on one of the template workflows and added it?

Made a PR to remove it #7

**Comment by ElectronicsArchiver** [comment]
Besides that, I manually reran the workflow
I created to overwrite what that Jerkyll
workflow added, the page is now live:

https://nptnk.github.io/
